name: robotChess
channels:
  - anaconda
  - conda-forge
  - menpo
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - absl-py=1.1.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.6.1
  - aom=3.4.0
  - asgiref=3.5.2
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - black=22.6.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cryptography=37.0.1
  - dataclasses=0.8
  - expat=2.4.8
  - fastapi=0.79.0
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - frozenlist=1.3.0
  - gast=0.5.3
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.7.6
  - google-auth=2.9.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpc-cpp=1.45.2
  - grpcio=1.45.0
  - h11=0.13.0
  - h5py=3.7.0
  - harfbuzz=4.4.1
  - hdf5=1.12.1
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - jasper=2.0.33
  - jpeg=9e
  - keras=2.8.0
  - keras-preprocessing=1.1.2
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.72.1
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.47.0
  - libopencv=4.5.5
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libssh2=1.10.0
  - libtasn1=4.18.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markdown=3.3.7
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nettle=3.8
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.2.0
  - openh264=2.2.0
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - p11-kit=0.24.1
  - pathspec=0.9.0
  - pcre=8.45
  - pillow=9.0.1
  - pip=22.1.2
  - pixman=0.40.0
  - platformdirs=2.5.2
  - protobuf=3.20.1
  - py-opencv=4.5.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydantic=1.9.1
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.5
  - python-flatbuffers=2.0
  - python_abi=3.10
  - pyu2f=0.1.5
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.0
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scipy=1.8.1
  - setuptools=61.2.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - sqlite=3.38.5
  - starlette=0.19.1
  - svt-av1=1.1.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.8.1
  - tensorflow-base=2.8.1
  - tensorflow-estimator=2.8.1
  - termcolor=1.1.0
  - tk=8.6.12
  - tomli=2.0.1
  - typed-ast=1.5.4
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.9
  - uvicorn=0.18.2
  - werkzeug=2.1.2
  - wheel=0.37.1
  - wrapt=1.14.1
  - x264=1!161.3030
  - x265=3.5
  - xz=5.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
